import fs from 'node:fs';
import {defs,scenes} from './peeps-art.mjs';
const main=`<div id="root" data-composition-id="weave" data-start="0" data-duration="15.6" data-width="1440" data-height="900"><svg class="symbols" aria-hidden="true">${defs}</svg><header class="mast"><div class="event">NEXT K-CORE<br>AI CONNECT</div><div class="mast-middle">GAME · ART · STORY<br><span>서로 다른 창작이 만나는 자리</span></div><div class="brand">SOYLAB<span>사람을 모으고, 함께하는 자리</span></div></header><div class="controls"><span>2026 / SEOUL</span><div><button id="pause" aria-label="모션 일시정지">일시정지</button><button id="replay" aria-label="모션 다시보기">다시보기 ↻</button></div></div><div id="motion-stage" class="stage clip" data-start="0" data-duration="15.6" data-track-index="1">${scenes.map((s,i)=>`<section class="scene s${i+1} ${s.id} ${s.light?'light':''}" style="background:${s.bg};--line-paper:${s.bg};--line-ink:${s.light ? '#FFFFFF' : '#111111'}"><p class="caption">${s.caption}</p><span class="scene-num">${s.n}</span><div class="artboard">${s.art}</div></section>`).join('')}</div><footer class="info"><p class="description">게임·예술·이야기, 전시·상영·강의·교류를 잇는 AI 창작 통합 행사</p><div class="facts"><div><strong>2026.12.09–10</strong><span>DDP 디자인랩 3층 디자인홀</span></div><p class="hours">일반 관람 <span>12/9 10:30–19:40</span><span>12/10 15:00–19:40</span></p><nav><a href="#program" target="_parent">프로그램 보기 ↗</a><a href="#guide" target="_parent">참여 안내 ↓</a></nav></div></footer><div class="progress"></div></div>`;
const css=fs.readFileSync(new URL('poster.css',import.meta.url),'utf8');
const motion=fs.readFileSync(new URL('peeps-motion.js',import.meta.url),'utf8');
function document(body,live=false){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SOYLAB / WEAVE TOGETHER</title><script src="assets/gsap.min.js"></script><style>${css}</style></head><body class="${live?'live':'render'}">${body}${live?`<main class="below"><section id="program"><h2>게임 · 예술 · 이야기를 함께</h2><p>전시·상영·강의·교류를 잇는 AI 창작 통합 행사입니다. 상세 프로그램과 강의 신청 링크는 추후 공개됩니다.</p></section><section id="guide"><h2>참여 안내</h2><p>2026.12.09–10 / DDP 디자인랩 3층 디자인홀</p><p>일반 관람: 12/9 10:30–19:40, 12/10 15:00–19:40</p><p>기업 참여는 확정되지 않았으며, 구체적인 참여 방법은 추후 안내됩니다.</p></section></main>`:''}<script>${motion}</script>${live?'<script src="live.js"></script>':''}</body></html>`;}
fs.writeFileSync(new URL('index.html',import.meta.url),document(main));
fs.writeFileSync(new URL('header-a.html',import.meta.url),document(main.replace(' data-composition-id="weave"',''),true));
fs.mkdirSync(new URL('mobile/',import.meta.url),{recursive:true});
fs.writeFileSync(new URL('mobile/index.html',import.meta.url),document(main.replace('data-width="1440" data-height="900"','data-width="390" data-height="844"')));
fs.cpSync(new URL('assets/',import.meta.url),new URL('mobile/assets/',import.meta.url),{recursive:true});
fs.copyFileSync(new URL('hyperframes.json',import.meta.url),new URL('mobile/hyperframes.json',import.meta.url));
console.log('Built six original SVG scenes, live header and mobile render.');
