import fs from 'node:fs';
const dir=new URL('./',import.meta.url);
const css=fs.readFileSync(new URL('stage.css',dir),'utf8');
const motion=fs.readFileSync(new URL('build.js',dir),'utf8');
const pauseIcon='<svg class="pause-icon" viewBox="0 0 20 20" aria-hidden="true"><path d="M7 4v12M13 4v12"/></svg><svg class="play-icon" viewBox="0 0 20 20" aria-hidden="true"><path d="M6 3.5 15 10 6 16.5Z"/></svg>';
const replayIcon='<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M4.2 7A6 6 0 1 1 4 12M4 3v4h4"/></svg>';
const inner=`<div id="human-scene" class="scene-mount" aria-hidden="true" data-layout-ignore></div><div class="poster-layout"><header class="topline"><h1 class="slogan"><span>AI를 사이에 두고,</span><span>사람과 사람이 만나다.</span></h1><div class="event-facts"><time class="date" datetime="2026-12-09">2026.12.09–10</time><p class="venue">DDP 디자인랩 3층 디자인홀</p></div></header><div aria-hidden="true"></div><footer class="bottomline"><div class="identity"><span class="brand">SOYLAB</span><span class="event-name">NEXT K-CORE AI CONNECT</span></div><div class="player-controls"><button class="control" id="human-pause" type="button" aria-label="모션 재생" aria-pressed="true" title="모션 재생">${pauseIcon}</button><button class="control" id="human-replay" type="button" aria-label="모션 처음부터 다시보기" title="모션 처음부터 다시보기">${replayIcon}</button></div><nav class="actions" aria-label="행사 안내"><a href="#program" target="_parent">프로그램 보기<span class="arrow" aria-hidden="true">↗</span></a><a href="#guide" target="_parent">참여 안내<span class="arrow" aria-hidden="true">↗</span></a></nav></footer></div><p class="sr-only" data-layout-ignore>하나의 구슬이 HUMAN에서 출발해 AI를 경유하고 HUMAN으로 돌아옵니다.</p>`;
const head='<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>SOYLAB — HUMAN / AI / HUMAN</title>';
function livePage(){return `<!doctype html><html lang="ko"><head>${head}<style>${css}</style><script src="assets/gsap.min.js"></script><script src="assets/three.min.js"></script></head><body class="live"><main id="stage"><section id="human-poster-root">${inner}</section></main><script src="scene.js"></script><script>${motion}</script><script src="player.js"></script></body></html>`;}
function renderPage(width,height){return `<!doctype html><html lang="ko"><head>${head}<style>html,body{margin:0;width:100%;height:100%;background:#090909}#stage{position:relative;width:100%;height:100%;overflow:hidden}#human-poster{position:absolute;inset:0}</style><script src="assets/gsap.min.js"></script></head><body class="render"><main id="stage" data-composition-id="human-return" data-start="0" data-duration="9" data-fps="30" data-width="${width}" data-height="${height}"><div id="human-poster" class="clip" data-composition-id="human-poster" data-composition-src="compositions/human-poster.html" data-start="0" data-duration="9" data-track-index="0" data-width="${width}" data-height="${height}"></div></main><script>const master=gsap.timeline({paused:true});master.to({t:0},{t:9,duration:9,ease:'none'});window.__timelines=window.__timelines||{};window.__timelines['human-return']=master;master.seek(0);</script></body></html>`;}
function composition(width,height){const posterInner=inner.replace(/<div class="player-controls">.*?<\/div>/,'<div class="player-controls" aria-hidden="true"></div>');return `<!doctype html><html lang="ko"><head><meta charset="utf-8"></head><body><template><style>${css}</style><section id="human-poster-root" data-composition-id="human-poster" data-width="${width}" data-height="${height}" data-duration="9">${posterInner}</section><script src="assets/three.min.js"></script><script src="scene.js"></script><script>${motion}</script></template></body></html>`;}
function writeRender(target,width,height){fs.mkdirSync(new URL('compositions/',target),{recursive:true});fs.writeFileSync(new URL('index.html',target),renderPage(width,height));fs.writeFileSync(new URL('compositions/human-poster.html',target),composition(width,height));}
writeRender(dir,1600,640);
fs.writeFileSync(new URL('header-human.html',dir),livePage());
const mobile=new URL('mobile/',dir);fs.mkdirSync(mobile,{recursive:true});
writeRender(mobile,390,720);
for(const file of ['scene.js','hyperframes.json'])if(fs.existsSync(new URL(file,dir)))fs.copyFileSync(new URL(file,dir),new URL(file,mobile));
fs.cpSync(new URL('assets/',dir),new URL('assets/',mobile),{recursive:true});
console.log('Built HUMAN return: 1600×640 / 390×720 / 9 seconds.');
