(function(){
  'use strict';
  const root=document.getElementById('root');
  const mobile=Number(root.dataset.width)<701 || window.innerWidth<701;
  const tl=gsap.timeline({paused:true});
  const purple='#7A00EE', paper='#F3F0E9', ink='#17151A';
  let previousState=null;
  const switchTo=(state,time,bg,fg,buttonInk)=>{
    if(previousState)tl.set(previousState,{opacity:0},time);
    tl.set(state,{opacity:1},time);
    tl.set(root,{backgroundColor:bg,'--fg':fg,'--button-ink':buttonInk},time);
    previousState=state;
  };
  switchTo('.s1',0,purple,paper,purple);
  tl.fromTo('.s1 .person-a .glyph',{yPercent:28,rotation:-7,opacity:0},{yPercent:0,rotation:0,opacity:1,duration:.66,stagger:.09,ease:'back.out(1.5)'},0);
  tl.fromTo('.s1 .person-b .glyph',{yPercent:-28,rotation:7,opacity:0},{yPercent:0,rotation:0,opacity:1,duration:.66,stagger:.09,ease:'back.out(1.5)'},.18);
  tl.fromTo('.s1 .bridge',{scaleX:0},{scaleX:1,duration:.48,ease:'power3.inOut'},.55);
  tl.to('.s1 .bridge',{scaleX:0,duration:.25,ease:'power2.in'},1.03);
  tl.fromTo('.s1 .small-ai',{scale:0,rotation:-90},{scale:1,rotation:0,duration:.55,ease:'back.out(1.5)'},1.05);
  tl.to('.s1 .person-a',{xPercent:mobile?-8:-5,duration:.5,ease:'power3.inOut'},1.7);
  tl.to('.s1 .person-b',{xPercent:mobile?8:5,duration:.5,ease:'power3.inOut'},1.7);
  tl.to('.s1 .person-a',{xPercent:-35,opacity:0,duration:.3,ease:'power3.in'},2.3);
  tl.to('.s1 .person-b',{xPercent:35,opacity:0,duration:.3,ease:'power3.in'},2.3);
  switchTo('.s2',2.6,paper,ink,paper);
  tl.fromTo('.s2 .space-a',{xPercent:40,rotation:8},{xPercent:0,rotation:0,duration:.65,ease:'power4.out'},2.6);
  tl.fromTo('.s2 .space-b',{xPercent:-40,rotation:-8},{xPercent:0,rotation:0,duration:.65,ease:'power4.out'},2.6);
  tl.fromTo('.s2 .small-ai',{scale:.1,opacity:0},{scale:1,opacity:1,duration:.4,ease:'back.out(1.5)'},2.96);
  tl.fromTo('.s2 .sub',{y:30,opacity:0},{y:0,opacity:1,duration:.48,ease:'power3.out'},3.28);
  tl.to('.s2 .space-a',{xPercent:-8,duration:.4,ease:'power2.inOut'},4.15);
  tl.to('.s2 .space-b',{xPercent:8,duration:.4,ease:'power2.inOut'},4.15);
  tl.to('.s2 .state-inner',{yPercent:-15,opacity:0,duration:.26,ease:'power3.in'},4.94);
  switchTo('.s3',5.2,ink,paper,ink);
  tl.fromTo('.s3 .g1',{xPercent:-65,skewX:-14,opacity:0},{xPercent:0,skewX:0,opacity:1,duration:.5,ease:'power4.out'},5.2);
  tl.fromTo('.s3 .g2',{yPercent:24,scaleY:1.1,opacity:0},{yPercent:0,scaleY:1,opacity:1,duration:.55,ease:'back.out(1.15)'},5.32);
  tl.fromTo('.s3 .discipline',{x:80,opacity:0},{x:0,opacity:1,duration:.45,stagger:.16,ease:'power3.out'},5.85);
  tl.fromTo('.s3 .sub',{opacity:0},{opacity:1,duration:.4},6.35);
  tl.to('.s3 .creative',{scale:.88,transformOrigin:'left center',duration:.35,ease:'power2.inOut'},7.1);
  tl.to('.s3 .state-inner',{xPercent:15,opacity:0,duration:.26,ease:'power3.in'},7.54);
  switchTo('.s4',7.8,purple,paper,purple);
  tl.fromTo('.s4 .join-a',{xPercent:-55,yPercent:-15,rotation:-10,opacity:0},{xPercent:0,yPercent:0,rotation:0,opacity:1,duration:.65,ease:'back.out(1.35)'},7.8);
  tl.fromTo('.s4 .join-b',{xPercent:55,yPercent:15,rotation:10,opacity:0},{xPercent:0,yPercent:0,rotation:0,opacity:1,duration:.65,ease:'back.out(1.35)'},7.9);
  tl.fromTo('.s4 .accent-line',{scaleX:0},{scaleX:1,duration:.35,ease:'power3.out'},8.55);
  tl.fromTo('.s4 .sub',{y:20,opacity:0},{y:0,opacity:1,duration:.48,ease:'power3.out'},8.75);
  tl.to('.s4 .together',{scale:.98,duration:.22,ease:'power2.inOut'},9.6);
  tl.to('.s4 .state-inner',{scale:1.07,opacity:0,duration:.25,ease:'power3.in'},10.15);
  switchTo('.s5',10.4,paper,ink,paper);
  tl.fromTo('.s5 .preline',{y:20,opacity:0},{y:0,opacity:1,duration:.42,ease:'power3.out'},10.4);
  tl.fromTo('.s5 .people-unit:first-child',{x:mobile?-30:-60,y:16,opacity:0},{x:0,y:0,opacity:1,duration:.65,ease:'power4.out'},10.55);
  tl.fromTo('.s5 .people-unit:last-child',{x:mobile?30:60,y:-16,opacity:0},{x:0,y:0,opacity:1,duration:.65,ease:'power4.out'},10.69);
  tl.fromTo('.s5 .meet',{y:30,opacity:0},{y:0,opacity:1,duration:.6,ease:'power4.out'},10.95);
  tl.fromTo('.s5 .invitation',{y:15,opacity:0},{y:0,opacity:1,duration:.6,ease:'power3.out'},11.2);
  tl.fromTo('.progress',{scaleX:0},{scaleX:1,duration:14,ease:'none'},0);
  window.__timelines=window.__timelines||{};
  window.__timelines['type-poster']=tl;
  window.posterTimeline=tl;
})();
