import fs from 'node:fs';
const dir=new URL('./',import.meta.url);
const css=fs.readFileSync(new URL('stage.css',dir),'utf8');
const waveCss=fs.readFileSync(new URL('wave.css',dir),'utf8');
const motion=fs.readFileSync(new URL('build.js',dir),'utf8');
const inner=`<div id="stage"><canvas id="world" aria-hidden="true" data-layout-ignore></canvas></div><div id="human-scene" aria-hidden="true" data-layout-ignore></div><div class="intro-meta"><header class="intro-copy"><div class="intro-kicker intro-line">NEXT K-CORE AI CONNECT</div><div class="intro-slogan"><span class="intro-line">AI를 사이에 두고,</span><span class="intro-line">사람과 사람이 만나다.</span></div></header><div class="intro-schedule"><div class="intro-date intro-line">2026.12.09–10</div><div class="intro-place intro-line">DDP 디자인랩 3층 디자인홀</div></div></div><div class="brand-mark" data-layout-ignore><img src="assets/soylab-logo.png" alt="SOY.LAB"></div><div id="typewave" aria-hidden="true" data-layout-ignore></div><section id="poster"><p class="label">NEXT K-CORE AI CONNECT</p><h1><span>AI를 사이에 두고,</span><span>사람과 사람이 <strong>만나다.</strong></span></h1><p class="poster-description">게임·예술·이야기의 전시·상영·강의·교류</p><div class="details"><div><div class="date">2026.12.09–10</div><div class="place">DDP 디자인랩 3층 디자인홀</div></div><nav class="actions" aria-label="행사 안내"><a href="#program" target="_parent">프로그램 보기 ↗</a><a href="#guide" target="_parent">관람 안내 ↘</a></nav></div></section><p class="sr-only" data-layout-ignore>작은 점들이 SOYLAB 글자에 색을 더하고, 하나의 구슬이 HUMAN에서 AI를 거쳐 HUMAN으로 돌아온 뒤 행사 포스터로 이어집니다.</p>`;
const posterInner=inner.replace('<h1><span>AI를 사이에 두고,</span><span>사람과 사람이 <strong>만나다.</strong></span></h1>','<h1>AI를 사이에 두고,<br>사람과 사람이 <strong>만나다.</strong></h1>');
const controls='<div class="controls"><span id="motion-status" aria-live="polite">20초 · 한 번 재생</span><button id="pause" type="button" aria-label="모션 일시정지">일시정지</button><button id="replay" type="button" aria-label="모션 처음부터 다시 재생">다시 재생 ↺</button></div>';
const head='<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>SOYLAB · 사람과 사람이 만나다</title>';
const sources=['assets/three.min.js','assets/logo-glyphs.js','wave.js','c-scene.js','human-scene.js','integrated-scene.js'];
const scripts=sources.map(src=>`<script src="${src}"></script>`).join('');
function livePage(){return `<!doctype html><html lang="ko"><head>${head}<style>${css}\n${waveCss}</style><script src="assets/gsap.min.js"></script></head><body class="web"><main id="convergence"><div id="integrated-root">${posterInner}${controls}</div></main>${scripts}<script>${motion}</script><script src="player.js"></script></body></html>`;}
function renderPage(width,height){return `<!doctype html><html lang="ko"><head>${head}<style>html,body{margin:0;width:100%;height:100%;background:#111}#convergence{position:relative;width:100%;height:100%;overflow:hidden}#integrated-poster{position:absolute;inset:0}</style><script src="assets/gsap.min.js"></script></head><body class="render"><main id="convergence" data-composition-id="integrated-header" data-start="0" data-duration="20" data-fps="30" data-width="${width}" data-height="${height}"><div id="integrated-poster" class="clip" data-composition-id="integrated-poster" data-composition-src="compositions/integrated-poster.html" data-start="0" data-duration="20" data-track-index="0" data-width="${width}" data-height="${height}"></div></main><script>const master=gsap.timeline({paused:true});master.to({t:0},{t:20,duration:20,ease:'none'});window.__timelines=window.__timelines||{};window.__timelines['integrated-header']=master;master.seek(0);</script></body></html>`;}
function composition(width,height){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"></head><body><template><style>${css}\n${waveCss}</style><div id="integrated-root" data-composition-id="integrated-poster" data-duration="20" data-width="${width}" data-height="${height}">${posterInner}</div>${scripts}<script>${motion}</script></template></body></html>`;}
function writeRender(target,width,height){fs.mkdirSync(new URL('compositions/',target),{recursive:true});fs.writeFileSync(new URL('index.html',target),renderPage(width,height));fs.writeFileSync(new URL('compositions/integrated-poster.html',target),composition(width,height));}
writeRender(dir,1600,640);
fs.writeFileSync(new URL('header-integrated.html',dir),livePage());
const mobile=new URL('mobile/',dir);fs.mkdirSync(mobile,{recursive:true});writeRender(mobile,390,720);
for(const file of ['c-scene.js','human-scene.js','integrated-scene.js','wave.js','wave.css','hyperframes.json'])if(fs.existsSync(new URL(file,dir)))fs.copyFileSync(new URL(file,dir),new URL(file,mobile));
fs.cpSync(new URL('assets/',dir),new URL('assets/',mobile),{recursive:true});
console.log('Built integrated C: 1600×640 / 390×720 / 20 seconds.');
