import fs from 'node:fs';
const here=new URL('./',import.meta.url);fs.mkdirSync(new URL('assets/',here),{recursive:true});
for(const file of ['gsap.min.js'])fs.copyFileSync(new URL('../assets/'+file,here),new URL('assets/'+file,here));
for(const file of ['IBMKR-SemiBold.woff2','Outfit.ttf'])fs.copyFileSync(new URL('../../concept-c-convergence/assets/'+file,here),new URL('assets/'+file,here));
function asset(id){let raw=fs.readFileSync(new URL('../assets/open-peeps/peep-standing-'+id+'.svg',here),'utf8');raw=raw.replace(/#FFFFFF/gi,'#CCFF00').replace(/#000000/gi,'#111111');fs.writeFileSync(new URL('assets/person-'+id+'.svg',here),raw);return raw.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/).slice(1).map(Number);}
const a=asset(24),b=asset(18);fs.copyFileSync(new URL('../hyperframes.json',here),new URL('hyperframes.json',here));
fs.writeFileSync(new URL('index.html',here),`<!doctype html><html lang="ko"><head><meta charset="utf-8"><script src="assets/gsap.min.js"></script><style>@font-face{font-family:Outfit;src:url(assets/Outfit.ttf)}@font-face{font-family:IBM;src:url(assets/IBMKR-SemiBold.woff2);font-weight:600}*{box-sizing:border-box}body{margin:0;background:#CCFF00;color:#111;font-family:IBM,sans-serif}#root{position:relative;width:1600px;height:640px;overflow:hidden}canvas{position:absolute;inset:0;width:100%;height:100%}header{position:absolute;top:40px;left:45px;right:45px;display:flex;justify-content:space-between;font:600 24px Outfit,sans-serif}.note{position:absolute;left:45px;bottom:35px;font-size:17px}.floor{position:absolute;left:160px;right:160px;top:525px;height:1px;background:#111;opacity:.4}</style></head><body><div id="root" data-composition-id="a-motion-test" data-start="0" data-duration="4" data-width="1600" data-height="640"><header><span>A / CHARACTER MOTION TEST</span><span id="phase">WALK</span></header><div class="floor"></div><canvas id="rig" width="1600" height="640"></canvas><p class="note">걷기 · 멈춤 · 손짓 · 응답 / 기존 선화를 유지한 관절 변형 테스트</p></div><script src="rig.js"></script><script>ARig.load('assets/person-24.svg',${a[0]},${a[1]},400,110,.60,'walker');ARig.load('assets/person-18.svg',${b[0]},${b[1]},880,117,.60,'listener');const ph={t:0};const tl=gsap.timeline({paused:true,onUpdate:()=>ARig.seek(ph.t)});tl.to(ph,{t:4,duration:4,ease:'none'});window.__timelines={'a-motion-test':tl};</script></body></html>`);console.log(a,b);


